export type ThemeColorsType =
  | 'primary'
  | 'primary-dark'
  | 'secondary'
  | 'secondary-dark'
  | 'black-dark'
  | 'gray-default'
  | 'gray-normal'
  | 'gray-lightest'
  | 'gray-lighter'
  | 'gray-light'
  | 'gray-medium'
  | 'gray-dark'
  | 'gray-darker'
  | 'white'
  | 'black';
